## Tensors and TensorFlow Basics

We will cover following topics in this notebook - 

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using GPUs

## Introduction to tensors

In [6]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [7]:
# Creating tensors - Generally won't create a tensor by yourself, mostly tensors will come from data like images, embeddings yada yada

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# Check the dimensions of the tensor
# If you don't understand why the output should be zero, check out Dan's YouTube video "What is a Tensor"
scalar.ndim

0

In [9]:
# Let's create another tensor

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Let's check the dims again
vector.ndim

1

In [12]:
# Let's create another tensor

vector = tf.constant([10, 10, 10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [13]:
# Let's check the dims again
vector.ndim

1

In [14]:
# Notice that it's still dim 1 tensor. Don't confuse tensor ranks with coordinates or other things. 
# A tensor rank is simply the number of directional indicator (or basis vector) per component
# For the above, we still only need 1 index per direction (x, y or z) and hence rank 1 tensor

# A non "scientific" but working way to understand a tensor is to count how many steps you need to access that element in the matrix

In [15]:
# Another tensor

matrix = tf.constant([[10,10], [10,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [16]:
matrix.ndim

2

In [ ]:
# It might be easier now to understand why it's rank 2 tensor. [[Axx, Axy], [Ayx, Ayy]]

In [17]:
# Keep on going

another_matrix = tf.constant([[1,2,3,4],
                              [2,3,4,5],
                              [3,4,5,6],
                              [4,5,6,7]])
another_matrix

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]], dtype=int32)>

In [18]:
another_matrix.ndim

2

In [ ]:
# Surprise surprise!! Still a rank 2 tensor
# By the method of no. of elements to reach any element, we still only need 2 values - Stack number and position in the stack!

In [19]:
# still, keep going

tensor = tf.constant([[[1,2], 
                          [2,3]],
                      [[5,6], 
                          [7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [20]:
tensor.ndim

3

In [ ]:
# Here it gets an upgrade - 
# Now we need more elements to reach a data point - 
# Which 1 of the 2 sub-arrays
# Which stack in the sub-array
# Which position in the stack!

Checkpoint - 

* Scalar - Single number (just magnitude)
* Vector - Number with a direction (Force and Direction in which force is applied)
* Matrix - 2-Dimensional array of numbers
* Tensor - n-Dimensional array of numbers

Let's create tensors using `tf.Variable`

In [21]:
# Let's create 2 tensors - using tf.Variable and tf.constant. Notice the difference in the output
mutable_tensor = tf.Variable([10, 8])
immutable_tensor = tf.constant([10, 8])

mutable_tensor, immutable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [22]:
# How to update the tensor?
# Usual index and assign like "tensor[0]=9" doesn't work, we have a method - assign()

mutable_tensor[0].assign(1)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 8], dtype=int32)>

In [ ]:
# Above code, obviously won't work with tf.constant

Create Random tensors - we'll need this a lot.

In practice, this is used in for example in creating weight array for the neural network with random numbers

In [24]:
# This creates a "generator" object - we initialize the generator object with seed for reproducibility
g = tf.random.Generator.from_seed(42)

# Next, using the "generator" object created above, create a random tensor whose elements are distributed normally
rnd_tensor = g.normal(shape=[3,4])

rnd_tensor, rnd_tensor.ndim

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, 2)

In [ ]:
# Won't lie, but that was AWESOME!!

In [25]:
# Lastly, let's test the seed!
g = tf.random.Generator.from_seed(42)
random_tensor_1 = g.normal(shape=[3,4])
random_tensor_2 = g.normal(shape=[3,4])

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 1.2866228 , -0.714756  , -0.1019548 ,  0.3831789 ],
        [-0.31881508, -0.3712327 , -0.29559934,  0.321117  ],
        [ 1.0777321 ,  0.23485184,  0.25318494,  0.36563298]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])>)

In [ ]:
# Above shows that TF doesn't have 1 matrix per seed (WOWWW, discovery!!!)

In [26]:
# Try something that makes sense!!
g1 = tf.random.Generator.from_seed(42)
random_tensor_1 = g1.normal(shape=[3,4])

g2 = tf.random.Generator.from_seed(42)
random_tensor_2 = g2.normal(shape=[3,4])

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [ ]:
# Yeah, thought so!!

### Shuffle tensors

It's a good idea to shuffle the input data set in order to provide random order of the classes (incase of Classifications) and not bombarding the model with same class over and over

In [27]:
actual_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6],
                            [7,8]])

# Shuffle the tensor
tf.random.shuffle(actual_tensor)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]], dtype=int32)>

Other ways to create a tensor

In [28]:
# create an array of all 1s . Pass dtype parameter to convert float32 to int
tf.ones(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [29]:
# create an array of all 0s
tf.zeros(shape=[4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Converting numpy arrays into tensors. 
Main Difference between numpy arrays and TF tensors is that tensors can be run on GPU for faster numerical processing

In [30]:
import numpy as np

numpy_A = np.arange(1, 25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
# Create the tensor from the numpy array as-is
as_is_shape = tf.constant(numpy_A)

# Create the tensor with custom shape
# Shape has to comply with the number of elements aXbXcXd....
custom_shape = tf.constant(numpy_A, shape = [3, 8])

as_is_shape, custom_shape

(<tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(3, 8), dtype=int64, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>)

In [56]:
# Other ways
tensor5 = tf.constant(np.array([1,2,3,4,5,6]))
np_array = np.array(tensor5)
other_way_to_get_np_array = tensor5.numpy()

type(tensor5), type(np_array), type(other_way_to_get_np_array)

(tensorflow.python.framework.ops.EagerTensor, numpy.ndarray, numpy.ndarray)

In [ ]:
#### Looks like and for obvious reasons, TF and numpy are very compatible. We'll keep pushing this to limits :D

## Getting information from tensors

#### But exactly what info??

* Shape
* Rank
* Axis
* Size

In [32]:
# Let's create a 4-D tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# We can use list-like, pandas-like indexing on these tensors

rank_4_tensor[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [34]:
print("tensor shape :", rank_4_tensor.shape)
print("tensor dimensions :", rank_4_tensor.ndim)
print("tensor size :", tf.size(rank_4_tensor))
print("tensor data type : ", rank_4_tensor.dtype)

tensor shape : (2, 3, 4, 5)
tensor dimensions : 4
tensor size : tf.Tensor(120, shape=(), dtype=int32)
tensor data type :  <dtype: 'float32'>


In [35]:
# tensor shape is NOT a tuple!
# tf.size is itself a tensor

type(rank_4_tensor.shape), type(rank_4_tensor.ndim), type(tf.size(rank_4_tensor))

(tensorflow.python.framework.tensor_shape.TensorShape,
 int,
 tensorflow.python.framework.ops.EagerTensor)

### Indexing tensors

In [36]:
# Let's create a rank 3 normal-random tensor 

g = tf.random.Generator.from_seed(42)

rank_3_tensor = g.normal(shape = [2,3,4])
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [37]:
# Get first 2 elements of every dimension

rank_3_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [-0.23193763, -1.8107855 ]],

       [[-0.3522796 ,  0.40621263],
        [ 1.6874489 , -0.4462975 ]]], dtype=float32)>

In [38]:
# Get all elements from each index except the final

rank_3_tensor[:-1, :-1, :-1]

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-0.23193763, -1.8107855 ,  0.09988727]]], dtype=float32)>

## Manipulating tensors

In [39]:
# Basic operation - +, -, *, /

tensor = tf.constant([[10,2], [2,6]])
tensor


tensor2 = tensor + 10
tensor, tensor2 # Addition is not inplace by default

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  2],
        [ 2,  6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 12],
        [12, 16]], dtype=int32)>)

In [40]:
tensor3 = tensor * 2

tensor, tensor3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  2],
        [ 2,  6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20,  4],
        [ 4, 12]], dtype=int32)>)

In [41]:
# tensorflow has built-ins for basics ops
tensor4 = tf.multiply(tensor, 10)
tensor, tensor4 # Still, not inplace by default

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  2],
        [ 2,  6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  20],
        [ 20,  60]], dtype=int32)>)

### Matrix multiplication

This is where tf wins, specially on GPUs

In [ ]:
## This code will throw an error

# tensor1 = g.normal(shape=[2,3])
# tensor2 = g.normal(shape=[2,3])

# tf.linalg.matmul(tensor1, tensor2)

In [42]:
# Yeah, doesn't work that way. 

# For matrices A(n1 X m1) and B(n2 X m2) to be able to be multipliable, m1 = n2 has to hold true.
# Output of A * B will be a matrix (or tensor) of the order of (n1 X m2)

tensor3 = g.normal(shape=[2,3])
tensor4 = g.normal(shape=[3,3])

tf.linalg.matmul(tensor3, tensor4)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.43815386,  0.09491348,  0.226129  ],
       [ 0.81179786, -0.5466475 , -1.0155652 ]], dtype=float32)>

In [43]:
# Lastly, about transposing and reshaping

tensor = g.normal(shape=[2,3])
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.47948825,  1.7463797 , -2.0002992 ],
       [ 0.49801555, -0.16169557, -0.01246966]], dtype=float32)>

In [44]:
tensor, tf.reshape(tensor, shape=[3,2]), tf.transpose(tensor)

# Notice the difference in outputs for reshape and transpose. 
# Reshape just takes matrix elements and starts filling the new shape. Transpose, however, has a rule and it flips the axes

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.47948825,  1.7463797 , -2.0002992 ],
        [ 0.49801555, -0.16169557, -0.01246966]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.47948825,  1.7463797 ],
        [-2.0002992 ,  0.49801555],
        [-0.16169557, -0.01246966]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.47948825,  0.49801555],
        [ 1.7463797 , -0.16169557],
        [-2.0002992 , -0.01246966]], dtype=float32)>)

 Also look into `tf.tensordot`

Checkpoint - 

* Mutable (Variable), Immutable (Constant) tensors
* Random, Shuffle, Zeros, Ones
* Matrix multiplication

### Data Types

In [45]:
# Let's create a tensor with default data type

tensor1 = tf.constant([[1,2] , [3,4]])
tensor1, tensor1.dtype

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, tf.int32)

In [46]:
# Default is 32-bit, whether float32 or int32. But 16-bit takes lesser memory and can be faster to process as well

tensor2 = tf.cast(tensor1, dtype = 'int16')
tensor2, tensor2.dtype

(<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[1, 2],
        [3, 4]], dtype=int16)>, tf.int16)

In [47]:
# Quick question - Can Tensors hold string values? or dates? Let's try to create one

str_tensor = tf.constant([['a', 'b'], 
                          ['c', 'd']])

str_tensor, str_tensor.dtype

# Absolutely, tensors can have any type of data type. How about mixed? - Nope
############ Following code will throw error

# mixed_tensor = tf.constant([['a', 1], 
#                           ['d', 1.234]])
# mixed_tensor, mixed_tensor.dtype

(<tf.Tensor: shape=(2, 2), dtype=string, numpy=
 array([[b'a', b'b'],
        [b'c', b'd']], dtype=object)>, tf.string)

It is not possible to create a tensor with mixed data types

Reference Link - https://stackoverflow.com/questions/49824872/convert-python-sequence-with-multiple-datatypes-to-tensor

Checkpoint - 

* Tensor Data Types
* Tensors can't hold multiple data types, but can hold int, float, str

### Tensor Aggregation

* Absolute value of the tensor
* Minimum value of the tensor
* Maximum value of the tensor
* Sum of the tensor
* Mean of the tensor

In [49]:
# Get the absolute values of a tensor

tensor = tf.constant([1, -7])
tensor, tf.abs(tensor)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, -7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [50]:
# tf.reduce_ seems a good choice
tf.reduce_max(tensor), tf.reduce_min(tensor), tf.reduce_mean(tensor), tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-6>)

### Finding positional max and min

For e.g., finding max prob in an output tensor of class probabilities in a multi-class classification

In [51]:
# Create a new tensor for positional min and max

index_tensor = tf.random.uniform(shape=[5,4])
index_tensor, tf.argmax(index_tensor)

# WHAT THE HELL!!!! It is giving the max along the column?

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[0.9555421 , 0.06692362, 0.23267794, 0.073125  ],
        [0.3389094 , 0.8672894 , 0.58685064, 0.07037997],
        [0.8507658 , 0.8746836 , 0.48133302, 0.01582861],
        [0.34682715, 0.9559239 , 0.95546746, 0.27702546],
        [0.672053  , 0.61518836, 0.3275069 , 0.2265321 ]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 3, 3, 3])>)

In [52]:
# What about an array
index_tensor = tf.random.uniform(shape=[5])
index_tensor, tf.argmax(index_tensor)

# This is fine!

(<tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([0.91354775, 0.73500323, 0.587468  , 0.5236143 , 0.21951354],
       dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [ ]:
# Naturally, tf.argmin gets us the minimum

### One-hot Encoding of Tensors

In [53]:
# Takes only numeric inputs. For text, we need to use Keras on top of this

labels = [1,2,3,4]

tf.one_hot(labels, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [54]:
### Square, Log and Root of tensors
### Notice the cheeky delta :D
tensor4 = tf.range(1, 20, delta=2)
tensor4

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int32)>

In [55]:
# tf.sqrt doesn't take int32 as an input - use cast to convert to one of the allowed values

tf.square(tensor4), tf.sqrt(tf.cast(tensor4, dtype=tf.float32)), tf.math.log(tf.cast(tensor4, dtype=tf.float32))

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.99999994, 1.7320508 , 2.236068  , 2.6457512 , 2.9999998 ,
        3.3166244 , 3.6055508 , 3.8729832 , 4.1231055 , 4.358899  ],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.       , 1.0986123, 1.609438 , 1.9459102, 2.1972246, 2.3978953,
        2.5649493, 2.7080503, 2.8332133, 2.944439 ], dtype=float32)>)

Boy, that's a lot of TensorFlow code!!