<a href="https://colab.research.google.com/github/suvigyajain0101/ML_with_TensorFlow/blob/main/00_TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors and TensorFlow Basics

We will cover following topics in this notebook - 

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using GPUs

## Introduction to tensors

In [6]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [7]:
# Creating tensors - Generally won't create a tensor by yourself, mostly tensors will come from data like images, embeddings yada yada

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# Check the dimensions of the tensor
# If you don't understand why the output should be zero, check out Dan's YouTube video "What is a Tensor"
scalar.ndim

0

In [9]:
# Let's create another tensor

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Let's check the dims again
vector.ndim

1

In [12]:
# Let's create another tensor

vector = tf.constant([10, 10, 10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [13]:
# Let's check the dims again
vector.ndim

1

In [14]:
# Notice that it's still dim 1 tensor. Don't confuse tensor ranks with coordinates or other things. 
# A tensor rank is simply the number of directional indicator (or basis vector) per component
# For the above, we still only need 1 index per direction (x, y or z) and hence rank 1 tensor

# A non "scientific" but working way to understand a tensor is to count how many steps you need to access that element in the matrix

In [15]:
# Another tensor

matrix = tf.constant([[10,10], [10,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [16]:
matrix.ndim

2

In [ ]:
# It might be easier now to understand why it's rank 2 tensor. [[Axx, Axy], [Ayx, Ayy]]

In [17]:
# Keep on going

another_matrix = tf.constant([[1,2,3,4],
                              [2,3,4,5],
                              [3,4,5,6],
                              [4,5,6,7]])
another_matrix

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]], dtype=int32)>

In [18]:
another_matrix.ndim

2

In [ ]:
# Surprise surprise!! Still a rank 2 tensor
# By the method of no. of elements to reach any element, we still only need 2 values - Stack number and position in the stack!

In [19]:
# still, keep going

tensor = tf.constant([[[1,2], 
                          [2,3]],
                      [[5,6], 
                          [7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [20]:
tensor.ndim

3

In [ ]:
# Here it gets an upgrade - 
# Now we need more elements to reach a data point - 
# Which 1 of the 2 sub-arrays
# Which stack in the sub-array
# Which position in the stack!

Checkpoint - 

* Scalar - Single number (just magnitude)
* Vector - Number with a direction (Force and Direction in which force is applied)
* Matrix - 2-Dimensional array of numbers
* Tensor - n-Dimensional array of numbers

Let's create tensors using `tf.Variable`

In [ ]:
# Let's create 2 tensors - using tf.Variable and tf.constant. Notice the difference in the output
mutable_tensor = tf.Variable([10, 8])
immutable_tensor = tf.constant([10, 8])

mutable_tensor, immutable_tensor

In [ ]:
# How to update the tensor?
# Usual index and assign like "tensor[0]=9" doesn't work, we have a method - assign()

mutable_tensor[0].assign(1)
mutable_tensor

In [ ]:
# Above code, obviously won't work with tf.constant

Create Random tensors - we'll need this a lot.

In practice, this is used in for example in creating weight array for the neural network with random numbers

In [ ]:
# This create a "generator" object - we initialize the generator object with seed for reproducibility
g = tf.random.Generator.from_seed(42)

# Next, using the "generator" object created above, create a random tensor whose elements are distributed normally
g.normal(shape=[3,4])

In [ ]:
# Won't lie, but that was AWESOME!!

In [ ]:
# Lastly, let's test the seed!
g = tf.random.Generator.from_seed(42)
random_tensor_1 = g.normal(shape=[3,4])
random_tensor_2 = g.normal(shape=[3,4])

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

In [ ]:
# Above shows that TF doesn't have 1 matrix per seed (WOWWW, discovery!!!)

In [ ]:
# Try something that makes sense!!
g1 = tf.random.Generator.from_seed(42)
random_tensor_1 = g1.normal(shape=[3,4])

g2 = tf.random.Generator.from_seed(42)
random_tensor_2 = g2.normal(shape=[3,4])

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

In [ ]:
# Yeah, thought so!!

### Shuffle tensors

It's a good idea to shuffle the input data set in order to provide random order of the classes (incase of Classifications) and not bombarding the model with same class over and over

In [ ]:
actual_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6],
                            [7,8]])

# Shuffle the tensor
tf.random.shuffle(actual_tensor)

Other ways to create a tensor

In [ ]:
# create an array of all 1s . Pass dtype parameter to convert float32 to int
tf.ones(shape=[3,4])

In [ ]:
# create an array of all 0s
tf.zeros(shape=[4,5])

### Converting numpy arrays into tensors. 
Main Difference between numpy arrays and TF tensors is that tensors can be run on GPU for faster numerical processing

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25)
numpy_A

In [ ]:
# Create the tensor from the numpy array as-is
as_is_shape = tf.constant(numpy_A)

# Create the tensor with custom shape
custom_shape = tf.constant(numpy_A, shape = [3, 8])

as_is_shape, custom_shape

In [ ]:
#### Looks like and for obvious reasons, TF and numpy are very compatible. We'll keep pushing this to limits :D

## Getting information from tensors

#### But exactly what info??

* Shape
* Rank
* Axis
* Size

In [ ]:
# Let's create a 4-D tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
# We can use list-like, pandas-like indexing on these tensors

rank_4_tensor[0][0]

In [ ]:
print("tensor shape :", rank_4_tensor.shape)
print("tensor dimensions :", rank_4_tensor.ndim)
print("tensor size :", tf.size(rank_4_tensor))
print("tensor data type : ", rank_4_tensor.dtype)

In [ ]:
# tensor shape is NOT a tuple!
# tf.size is itself a tensor

type(rank_4_tensor.shape), type(rank_4_tensor.ndim), type(tf.size(rank_4_tensor))

### Indexing tensors

In [ ]:
# Let's create a rank 3 normal-random tensor 

g = tf.random.Generator.from_seed(42)

rank_3_tensor = g.normal(shape = [2,3,4])
rank_3_tensor

In [ ]:
# Get first 2 elements of every dimension

rank_3_tensor[:2, :2, :2]

In [ ]:
# Get all elements from each index except the final

rank_3_tensor[:-1, :-1, :-1]

## Manipulating tensors

In [ ]:
# Basic operation - +, -, *, /

tensor = tf.constant([[10,2], [2,6]])
tensor


tensor2 = tensor + 10
tensor, tensor2 # Addition is not inplace by default

In [ ]:
tensor3 = tensor * 2

tensor, tensor3

In [ ]:
# tensorflow has built-ins for basics ops
tensor4 = tf.multiply(tensor, 10)
tensor, tensor4 # Still, not inplace by default

### Matrix multiplication

This is where tf wins, specially on GPUs

In [ ]:
## This code will throw an error

# tensor1 = g.normal(shape=[2,3])
# tensor2 = g.normal(shape=[2,3])

# tf.linalg.matmul(tensor1, tensor2)

In [ ]:
# Yeah, doesn't work that way. 

# For matrices A(n1 X m1) and B(n2 X m2) to be able to be multipliable, m1 = n2 has to hold true.
# Output of A * B will be a matrix (or tensor) of the order of (n1 X m2)

tensor3 = g.normal(shape=[2,3])
tensor4 = g.normal(shape=[3,3])

tf.linalg.matmul(tensor3, tensor4)

In [ ]:
################# The following code block throws error - Still lacking understanding on how higher rank tensor multiplication works
####################################################################################################################################
# # What about higher dimensions

# tensor5 = g.normal(shape = [2,3,4,5])
# tensor6 = g.normal(shape = [2,3,4,5])

# tf.linalg.matmul(tensor5, tensor6)

In [ ]:
# This needs to be looked into

In [ ]:
# Lastly, about transposing and reshaping

tensor = g.normal(shape=[2,3])
tensor

In [ ]:
tensor, tf.reshape(tensor, shape=[3,2]), tf.transpose(tensor)

# Notice the difference in outputs for reshape and transpose. 
# Reshape just takes matrix elements and starts filling the new shape. Transpose, however, has a rule and it flips the axes

 Also look into `tf.tensordot`

### Data Types

In [ ]:
# Let's create a tensor with default data type

tensor1 = tf.constant([[1,2] , [3,4]])
tensor1, tensor1.dtype

In [ ]:
# Default is 32-bit, whether float32 or int32. But 16-bit takes lesser memory and can be faster to process as well

tensor2 = tf.cast(tensor1, dtype = 'int16')
tensor2, tensor2.dtype

In [ ]:
# Quick question - Can Tensors hold string values? or dates? Let's try to create one

str_tensor = tf.constant([['a', 'b'], 
                          ['c', 'd']])

str_tensor, str_tensor.dtype

# Absolutely, tensors can have any type of data type. How about mixed? - Nope
############ Following code will throw error

# mixed_tensor = tf.constant([['a', 1], 
#                           ['d', 1.234]])
# mixed_tensor, mixed_tensor.dtype

It is not possible to create a tensor with mixed data types

Reference Link - https://stackoverflow.com/questions/49824872/convert-python-sequence-with-multiple-datatypes-to-tensor

### Tensor Aggregation

* Absolute value of the tensor
* Minimum value of the tensor
* Maximum value of the tensor
* Sum of the tensor
* Mean of the tensor

In [ ]:
# Get the absolute values of a tensor

tensor = tf.constant([1, -7])
tensor, tf.abs(tensor)

In [ ]:
# tf.reduce_ seems a good choice
tf.reduce_max(tensor), tf.reduce_min(tensor), tf.reduce_mean(tensor), tf.reduce_sum(tensor)

### Finding positional max and min

For e.g., finding max prob in an output tensor of class probabilities in a multi-class classification

In [ ]:
# Create a new tensor for positional min and max

index_tensor = tf.random.uniform(shape=[5,4])
index_tensor, tf.argmax(index_tensor)

# WHAT THE HELL!!!! It is giving the max along the column?

In [ ]:
# What about an array
index_tensor = tf.random.uniform(shape=[5])
index_tensor, tf.argmax(index_tensor)

# This is fine!

In [ ]:
# Naturally, tf.argmin gets us the minimum

### One-hot Encoding of Tensors

In [ ]:
# Takes only numeric inputs. For text, we need to use Keras on top of this

labels = [1,2,3,4]

tf.one_hot(labels, depth = 4)

In [ ]:
### Square, Log and Root of tensors

tensor4 = tf.range(1, 20, delta=2)
tensor4

In [ ]:
# tf.sqrt doesn't take int32 as an input - use cast to convert to one of the allowed values

tf.square(tensor4), tf.sqrt(tf.cast(tensor4, dtype=tf.float32)), tf.math.log(tf.cast(tensor4, dtype=tf.float32))

### Tensors and Numpy

TensorFlow and Numpy go hand in hand, I mean have a lot of compatibility. It's easy to create tensors from numpy array and vice versa

In [ ]:
import numpy as np

tensor5 = tf.constant(np.array([1,2,3,4,5,6]))
np_array = np.array(tensor5)
other_way_to_get_np_array = tensor5.numpy()

type(tensor5), type(np_array), type(other_way_to_get_np_array)

Boy, that's a lot of TensorFlow code!!